# Generated by Django 4.2.2 on 2023-06-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrapingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thumbnail", models.ImageField(upload_to="Thumbnail")),
                ("title", models.CharField(max_length=500)),
                ("rating", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
            ],
        ),
    ]
