# Generated by Django 4.2.2 on 2023-06-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapingdata",
            name="thumbnail",
            field=models.CharField(max_length=500),
        ),
    ]
