# Generated by Django 4.2.2 on 2023-06-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_scrapingdata_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapingdata",
            name="details",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
